### ISSUE TITLE
VSH menu doesn't show up on 3.61+ games

### ISSUE THREAD

**Issue by aspendable** [joel16/PSV-VSH-Menu#10]
VSH menu doesnt showed up on 3.61+ games. i tested SAO hollow realization and FATE EXTELLA. my fw is enso 3.65. and i tested eiyuu densetsu sora no kiseki SC evo and it did showed up. tested on vitashell too and it works. pls fix this. thanks a lot man u're the best!

**Comment by caladbolgII** [comment]
It's not working on akiba's beat and danganronpa v3. works with chaos child though

**Comment by dude22072** [comment]
Also having this issue on Itadaki Street 30th

**Comment by joel16** [comment]
Fixed with https://github.com/joel16/PSV-VSH-Menu/commit/943fd21b3303f1d9038dadca93c3b2942b8c3418
