### ISSUE TITLE
Error C2-12828 on PCSG01013 (Gun Gun Pixies)

### ISSUE THREAD

**Issue by despairoharmony** [joel16/PSV-VSH-Menu#11]
When game boot with the plugin its gives a C2-12828 error, I disable the plugin and the game run normally

**Comment by Dino1989** [comment]
I had similar problem, when I tried to bring up the vsh menu it would crash with it's own error code.

I fixed it by going to ur0:data and deleting the vsh folder through Vitashell, and then I rebooted the device through the Henkaku settings. I no longer have any issues as long as I don't go beyond the "white" selection under the vsh color menu. Other than that I have absolutely no issues. It might work for you too. God Speed!

**Comment by joel16** [comment]
@Dino1989 I'm going to be releasing a bug fix update pretty sure that addresses the issue with the colour selection. Sorry about that. I don't have too many games on my device to test (nor do I have the storage for it). I'll need to investigate further as to why it doesn't work with certain games.

**Comment by joel16** [comment]
Should be fixed with https://github.com/joel16/PSV-VSH-Menu/commit/943fd21b3303f1d9038dadca93c3b2942b8c3418 if not I'll re-open.
