### ISSUE TITLE
Game crash on change menu colour White/Red

### ISSUE THREAD

**Issue by puppydogpals** [joel16/PSV-VSH-Menu#12]
If you scroll past white on the VSH Menu colour using the right key to get to red from white it will cause a game crash.

If you press left from red to get to white it also crashes 

error code c2-12828-1

pch-1103 (3g phat)
3.65 enso
sd2vita
tai folder on ur0

also as previously mentioned in other issues wont run on some games, im guessing 3.61+ but can not confirm ATM

**Comment by joel16** [comment]
Are you using v2.1? The issue with colour should be fixed. Go to vitashell and delete ur0:/data/vsh. Then try again.

I'm not sure what's up with the 3.61 games, I'm gonna have to dig deeper.

**Comment by puppydogpals** [comment]
apologies I used a link from wololo that pointed me to version 2 on github not version 2.1. (should of clicked on releases to check for update first!!)

working now, Thanks
