### ISSUE TITLE
Plugin not showing for me on enso 3.65

### ISSUE THREAD

**Issue by skir0cket** [joel16/PSV-VSH-Menu#14]
Hi I can't seem to get this working I have the two plugins in ux0:tai/ and have my config as below?

*KERNEL
ux0:tai/kuio.skprx
ux0:tai/nonpdrm.skprx
ux0:tai/gamesd.skprx

*ALL
ux0:tai/vsh.suprx

*main
ux0:tai/shellbat.suprx
ux0:tai/download_enabler.suprx

*NPXS10015
ux0:tai/henkaku_sfc.suprx

*NPXS10016

**Comment by joel16** [comment]
Did you restart after adding the plugin into your config?
Also I can see that you have gamesd, does that mean you use one of those sd adapters?

**Comment by skir0cket** [comment]
hi yeah I have rebooted and still not working, was thinking it was something to do with my config, no I got the config from a forum after I somehow lost mine when I updated from 3.60 so I can just delete gamesd.

**Comment by joel16** [comment]
Ok, so are you using an SD2VITA adapter or anything? Because currently the plugin won't work if you are.

**Comment by skir0cket** [comment]
Nope I don't use any sd2vita adapter I only have my internal memory at the minute

**Comment by joel16** [comment]
Ok can you remove gamesd.skprx then reboot the device?
If the error persists let me know if there is a 'vsh' folder in ur0:/data/. Inside the vsh folder should be a config.cfg file as well as some others. Does that file exist? and if it does, is it empty?

**Comment by skir0cket** [comment]
I have removed the gamesd.skprx from my config, and rebooted, its still not working for me. I have a config.cfg file in ur0:/data/vsh which has this info
display_battery_percent = 0
display_battery_lifetiime = 0
display_battery_temp = 0 
display_battery_data = 0
Bar_colour_=8

**Comment by joel16** [comment]
Can you try running it on a homebrew? Presss L + R + Start on any homebrew like vitashell and see if it shows up

**Comment by skir0cket** [comment]
ok, seems to be working in VitaShell! tried in UCVSM3 and seems to be working as well now. thanks

**Comment by joel16** [comment]
Glad you got it working.

**Comment by lovelydumpling** [comment]
"Ok, so are you using an SD2VITA adapter or anything? Because currently the plugin won't work if you are."
Mind if I ask if there are plans to change this?

I'm also unable to get it to show up in games. I was able to get it to show up in Vitashell, but not Dragon Quest Builders (the only game I have that I can test it in atm.)

**Comment by joel16** [comment]
Probably not, I don't own one myself so I'd have to rely on someone else to test it. Also currently busy with school, so until I'm done (around May) you won't see much activity here.
