### ISSUE TITLE
Source of modified kuio.skprx?

### ISSUE THREAD

**Issue by satelliteseeker** [joel16/PSV-VSH-Menu#16]
Hello, I'm doing some research with the kuio plugin. Could you please upload the source of modified kuio used in PSV VSH Menu for better understanding of how it works? Thanks.

**Comment by joel16** [comment]
It does not add anything new it just removes ksceIoLseek, ksceIoRmdir, ksceIoRemove functions to make it lighter and specific for this plugin since it does not use those functions.

**Comment by satelliteseeker** [comment]
Thanks for the clarification.
