### ISSUE TITLE
Incompatible with Adrenaline

### ISSUE THREAD

**Issue by azumukupoe** [joel16/PSV-VSH-Menu#17]
When vsh.suprx is enabled under *ALL, the menu starts simultaneously with Adrenaline.
Also, scrolling does not work right in Adrenaline.

**Comment by joel16** [comment]
I still have yet to figure this out. This project is on hold until/if I figure out these issues.

You can do this for now:

*!PSPEMUCFW
*ALL
ur0:tai/vsh.suprx

**Comment by dude22072** [comment]
There is already an issue about Adrenaline compatibility ( See Issue #2 ).
This should have been placed there instead of a new issue being made.

**Comment by joel16** [comment]
Closing because like dude22072 said, this is a duplicate.

**Comment by azumukupoe** [comment]
@joel16 What could I do for Adrenaline bubbles?

**Comment by joel16** [comment]
Don't they take a certain titleID @azumukupoe

**Comment by azumukupoe** [comment]
@joel16 Okay, I wish that they make multiple ID support for halt points.
