### ISSUE TITLE
Request: Show framerate counter.

### ISSUE THREAD

**Issue by Duckbuster** [joel16/PSV-VSH-Menu#19]
I tried using this plugin together with: https://github.com/Rinnegatamante/Framecounter
But its not working for me.
VSH menu works, but not the framecounter.
Running 3.65 Enso.
So it would be nice to just put that functionality inside VSH menu. Like the battery stuff.

**Comment by joel16** [comment]
I believe there's a limit as to how many things can fit into the framebuffer. Last time I attempted this it messed up the menu, so I don't think this is going to work out anytime soon. Sorry about that.

**Comment by Duckbuster** [comment]
Thanks for the clarification on why it's not possible.
Thanks anyway!
