### ISSUE TITLE
Breaks Adrenaline when loaded under *ALL

### ISSUE THREAD

**Issue by dude22072** [joel16/PSV-VSH-Menu#2]
when VSH.suprx is loaded through *ALL in the taiHEN config.txt, adrenaline does not respond to any button presses. Interestingly, when I press X, it brings up the PSV WSH Recovery Menu. Removing VSH.suprx from the config.txt makes adrenaline work without issue, so this is certainly a problem caused by VSH.suprx

**Comment by dude22072** [comment]
Can confirm this issue still happens with Version 2.0 and Enso 3.65 and Adrenaline 6.1. Although, I no longer have the Recovery Menu installed, so pressing X just gives me a black screen.

**Comment by chrisfand** [comment]
Can confirm same issue. Workaround is to press the Circle button to regain button control in Adrenaline. It almost seems like the VSH menu is showing up as invisible or something when Adrenaline starts.

**Comment by shawly** [comment]
I'm on Enso 3.65 and VSH Menu 2.1 and I don't have this issue with Adrenaline 6.1 even though it's loaded under *ALL.
**But** if I start Adrenaline the VSH Menu instantly pops up even though I haven't pressed the key combo and the main issue is, it is super fast. If I press the D-pad up or down it recognizes my input multiple times so it jumps over 7-10 entries, sometimes it also recognizes pressing up or down as left or right, so the colors and the clock speed get changed even though I just want to navigate to the Exit. This doesn't happen with Vita games.

Guess I'll use *!PSPEMUCFW to exclude it from Adrenaline, but I wanted to let you know this is happening.

**Comment by Catarax** [comment]
All overclock tools break games in some ways on psp for vita actually.

**Comment by joel16** [comment]
No use in Adrenaline, use the following instructions to prevent it from loading in Adrenaline. https://github.com/joel16/PSV-VSH-Menu/commit/9b83194430bc5bfd20f999e25365fb10b7fad0cf
