### ISSUE TITLE
Doesn't work on H-ENORE with SD2VITA 3.68

### ISSUE THREAD

**Issue by Masters110** [joel16/PSV-VSH-Menu#22]
I put both files in ur0 ( this is where it goes for SD2VITA)

added the  *All vsh file

plugin is correctly installed but nothing happens when i press L+R + Start 

*KERNEL
ur0:tai/kuio.skprx

*ALL
ur0:tai/vsh.suprx

(restarted more than once since installing.

I am using StorageMgr for the sd2vita plugin. Gamesd didn't work.

**Comment by Masters110** [comment]
I'm new here I don't know how to delete this.

I fixed it. *ALL needs to be all caps



I got it working but  half of the menus are locked.

**Comment by joel16** [comment]
Sorry but I'm not sure how to get this working on SD2VITA. I have no idea how it works, and all the menus are locked because it's failing to store the config files. I'm working on another release that may fix it. Please wait until another release has been made.

**Comment by Masters110** [comment]
Oh right. Well SD2vita stores all plugins in Ur0:\Tai Etc

Ux0 = SD2vita card/Cart
Umr0 = memory card

**Comment by Masters110** [comment]
I think joel16 the best way to fix this for SD2VITA is stop it saving the config file.

**Comment by joel16** [comment]
That's not an option. The config file is crucial for this plugin.

**Comment by Masters110** [comment]
Thanks for the reply. One thing I tried is moving the data folder to ur0. It copied okay but still loaded data from Ux0

Anyways for now I will use oclockvita. I will check back for any updates. Thanks for the help.

**Comment by joel16** [comment]
Sorry about that, could you give the new release a try? https://github.com/joel16/PSV-VSH-Menu/releases/tag/3.00 I really do want to get this issue with SD2VITA sorted. The config is a must for this plugin because it would be a hassle if the user had to always set the options each time they start a new game.

**Comment by Masters110** [comment]
Sure I will post back here in a few mins and let you know how it goes.

**Comment by Masters110** [comment]
3.0 doesn't work at all for me. It stops games loading. They get stuck at the slash screen.

**Comment by joel16** [comment]
Did you put the config in ur0:tai or ux0:?

**Comment by Masters110** [comment]
Ur0

The config.txt is in ur0 because sd2vita doesn't work if its in Ux0

**Comment by joel16** [comment]
That's the problem, it is looking for the vsh.suprx in ur0:/ where it doesn't exit. I'm not really sure how SD2vita works, but can't you put the files in ux0:?

Edit: Just seeing your message, I'll send a new build that tries to load through ur0:/ in a bit.

**Comment by Masters110** [comment]
Yeah I just tried putting both files in Ux0 with the config in Ur0


Changed the config file to ux0:/tai


Games load but the vsh menu doesn't work at all. In ur0 they stop games loading.

**Comment by joel16** [comment]
Ok here's the one that loads everything from ur0:/
https://cdn.discordapp.com/attachments/209789013240840192/468464399619981323/vsh.zip

It also creates the config files in ur0:/ (Hopefully this works :/)

**Comment by Masters110** [comment]
It doesn't work at all but I checked my Ux0 folder under data and other plugins save data there and run from ur0
Savemgr is one of those plugins. Not sure if that helps at all.


SORRY  for slow reply the website was down.

**Comment by joel16** [comment]
@Masters110 Yeah I noticed.

Here's my final test for today. This one reverted back to KUIO, this time everything has to be in **ur0:/** again.

https://cdn.discordapp.com/attachments/209789013240840192/468474713509986314/vsh.zip

You'll need this in your ur0:tai/config.txt:

```
*KERNEL
ur0:tai/kuio.skprx

*ALL
ur0:tai/vsh.suprx
```

**Comment by Masters110** [comment]
The last one works.

**Comment by joel16** [comment]
Thank you, I'll make a proper release and close this once I push the commit :)

**Comment by Masters110** [comment]
No problem mate.  Good luck and thanks.

**Comment by joel16** [comment]
Thank you once again for taking your time out to test this. Much appreciated!
Fixed with https://github.com/joel16/PSV-VSH-Menu/commit/943fd21b3303f1d9038dadca93c3b2942b8c3418
