### ISSUE TITLE
Version 3.2 doesn't display the correct clock speeds.

### ISSUE THREAD

**Issue by liznaith** [joel16/PSV-VSH-Menu#24]
I know that once I overclock the system using the menu, it will overclock the system automatically everytime I boot up the game I want to play, however when I open the menu after rebooting a game, the clocks display as CPU 333/222 and GPU 166/166 instead of CPU 444/222 and GPU 222/166.

Probably the correct overclocks are in place, however what is written in the menu is not correct.

pls fix

**Comment by joel16** [comment]
Yeah the display is wrong but it properly clocks it to 444/222 if you check on VITAident. I'll look into it when I get time.

**Comment by joel16** [comment]
Should be fixed with https://github.com/joel16/PSV-VSH-Menu/releases/tag/3.30
