### ISSUE TITLE
PSV-VSH Menu in adrenaline

### ISSUE THREAD

**Issue by EzekielLati** [joel16/PSV-VSH-Menu#25]
So I found a bug when trying to open psv vsh in adrenaline and it won't appear but when I open the settings (ps button+select) it suddenly appeared then when pressing directional buttons to select, it scrolls too fast that it's hard to select exit especially if you press the left and right buttons because it changes the option while scrolling down fast

Give it a try, open psv vsh in adrenaline then go to it's settings

**Comment by Masters110** [comment]
You need to add !PSPEMUCFW  in the config. Not sure why you even want it
for psp games 333 is.more than enough.

**Comment by EzekielLati** [comment]
No I accidentally pressed it when I was playing khbb.
I locked on an enemy then press start for pausing :)
That triggered the menu

Thx for the solution though

**Comment by Masters110** [comment]
No problem mate. Let me know if that works. Yeah i had to put that in the
config  because it just pops up

**Comment by joel16** [comment]
No point in using this in adrenaline. Added the instructions to prevent it from working with adrenaline entirely. https://github.com/joel16/PSV-VSH-Menu/commit/9b83194430bc5bfd20f999e25365fb10b7fad0cf
