### ISSUE TITLE
Tearaway Camera function not working.

### ISSUE THREAD

**Issue by elFabin** [joel16/PSV-VSH-Menu#26]
Not sure if this is an issue with kuio or vsh, but I report it here anyway because is related.

The camera just output plain black image, when I open the camera app after suspending the game (PS Button) the output is buggy and has tearing.

**Comment by joel16** [comment]
Try this: Remove VSH from ur0:tai/config.txt and check if it happens. If it does it's a KUIO problem. But if you have vsh in, and remove kuio from config.txt then we'll know its a VSH problem.

**Comment by elFabin** [comment]
UPDATE: It was a VSH issue, but now it's fixed with version 3.4, Thanks for the answer.
