### ISSUE TITLE
Dimming on GPU overclock

### ISSUE THREAD

**Issue by guicogo** [joel16/PSV-VSH-Menu#27]
Is there a way to not dim the brightness on GPU overclock?

**Comment by joel16** [comment]
I'm not doing this. Sony's Clock setting functions seems to automatically do it. I would try to get around this but there's no way to get the current brightness unless you read the registry. Can't access registry in user-mode plugins.

**Comment by ghost** [comment]
https://github.com/ShroomKing/No-Lower-Brightness-Vita
Can be helpful (for both of you ;) ).

**Comment by guicogo** [comment]
@joel16 
Mary Skelter for some reason doesn't dim the brightness even at max overclock.
@kozarovv 
Thanks, but I've tried, it doesn't work with NoNpDrm.
