### ISSUE TITLE
Option to move the FPS counter to the top-left

### ISSUE THREAD

**Issue by liznaith** [joel16/PSV-VSH-Menu#29]
Back when I was using the Framecounter plugin, the FPS counter was always on the top-left, so I am always used to seeing it there.  I would like to have the option to move the FPS counter to the top-left since it seems to be a more reliable spot to view my FPS rather than the bottom of the screen.

**Comment by joel16** [comment]
I don't want to add more options {bulk} just for personal preference sorry.

**Comment by Masters110** [comment]
Liz If you really want to do it. Use the source code and do it yourself.
