### ISSUE TITLE
Adrenaline is laggy since v3.3

### ISSUE THREAD

**Issue by simonizer2409** [joel16/PSV-VSH-Menu#30]
Hi there (again),

when I run something in Adrenaline/PspEmu (NPXS10028), Adrenaline gets laggy. Animations still seem smooth, but transitions don't always do. It's especially noticable when switching from Adrenaline to the LiveArea screen.

This first occured in v3.3. It doesn't happen in v3.2.

System info:
- PlayStation Vita Slim
- Firmware: 3.65 Enso
- PSV-VSH-Menu: v3.3/3.4

**Comment by NeonLightning** [comment]
does
`!*PSPEMUCFW`
help?
 as adrenaline has its own vsh menu.

**Comment by joel16** [comment]
In the readme it's advised not to use this with adrenaline.
