### ISSUE TITLE
Games "default" to the wrong clock speed

### ISSUE THREAD

**Issue by Tomcoid** [joel16/PSV-VSH-Menu#37]
Hey, I've tested with both Uncharted:Golden abyss and Persona 3: Dancing moon night, and both default to 333mhz when they should be at 444. Additionally, from what I've seen, every game defaults at 333. Any advice?

**Comment by Tomcoid** [comment]
Further note: I assume those games should be at 444 because they lag on default with VSH active, yet don't when the plugin is inactive. So it's either wrong default speed or the plugin is causing a decent amount of lag

**Comment by joel16** [comment]
Yes I fixed that, and I'll make one final release. Can you test this to confirm it works fine? https://github.com/joel16/PSV-VSH-Menu/blob/gh-pages/vsh.suprx

**Comment by Tomcoid** [comment]
As far as I can tell, the two games, when set at default, run perfectly fine now. P3: Dancing moon night runs at the solid 30fps, and uncharted now stays at 30, except for when in combat, where it did dip to 27 at a point, however I would think that it's more or less normal

**Comment by Tomcoid** [comment]
However, If either of those games are supposed to run at 444, there is a problem in which default is set where 333 should be

**Comment by joel16** [comment]
the new build I sent earlier won't overclock/underclock if the 'default' option is on.

**Comment by Tomcoid** [comment]
Then we good fam, everything is great. Thanks!

**Comment by joel16** [comment]
No probs.
