### ISSUE TITLE
Vsh Menu with RetroArch

### ISSUE THREAD

**Issue by Astromatik** [joel16/PSV-VSH-Menu#4]
Is it possible to run vsh menu for retroarch?
The Overclocking give more performance for the retrogaming with shader.
Thank you

**Comment by joel16** [comment]
It should work, have you tried it?

**Comment by Astromatik** [comment]
Yes I try it but nothing coming up for the menu... 
In the config.txt, I don't write with *All
I really want try your menu for make more punch with retroarch. 
Thank you

**Comment by Astromatik** [comment]
I don t understand, any test but I can't see any menu on retroarch. In config.txt, What should I write. Thank you

**Comment by joel16** [comment]
Have you tried if oclockvita works on retroarch? Because I believe it was blocked from the drawing on the screen. If that's the case I don't think this will work.

Also in config.txt you should have: 

*GAMENAME
ux0:/tai/vsh.suprx

**Comment by noradninja** [comment]
I was able to get Retroarch overclocked on the PSTV/Vita via the following method:

Set up the overclock in a game the VSH menu works in.
In VItashell, go to **ur0:/data/vsh/titles**.
Copy the config file of the app you overclocked (in my case, I used **VITASHELL.cfg** to **ur0:/data/vsh/**.
Rename the file **RETROVITA.cfg**.
Copy RETROVITA.cfg back to  **ur0:/data/vsh/titles**.

Enjoy your now overclocked Retroarch. I have not tested things like shaders, etc with the OC, will see how it goes. When you first load, the GPU will be at normal clock but after about 3 seconds, it goes app to the 222/166 clock. 

Alternatively, you can just drop the attached RETROVITA.cfg into **ur0:/data/vsh/titles**, then load Retroarch. This clocks the CPU/GPU to max, you can verify this by using the VSH menu in another app like Vitashell to enable KEEP CLOCK DISPLAY and CLOCK DISPLAY so they show up when you load Retroarch. The fact that that the displays work makes me think that Retroarch is capturing the controls in a way that keeps the macro that loads PSV-VSH from working and has nothing to do with how PSV-VSH draws the menu.

![img_0187](https://user-images.githubusercontent.com/6692990/43530713-3b86b988-957c-11e8-8d49-526a7fcdeacd.jpeg)

[RETROVITA.cfg zip download](https://github.com/joel16/PSV-VSH-Menu/files/2250066/RETROVITA.cfg.zip)

**Comment by Astromatik** [comment]
Wouhhhhh Sound very good 👍. I ll test tonight.

Thank you very much

**Comment by noradninja** [comment]
FYI if you load any of the video filters, Retroarch will hang. I even tried returning it to the stock speeds and it still did it, so this will not help with using filters, but it should help with framerate issues, as RA doesn't seem to OC by default.

**Comment by Astromatik** [comment]
Maybe you can tell it at libretro team ! 
I think they must add glsl shader for run it but its a very good news Thank you

**Comment by noradninja** [comment]
Yeah I am gonna message them over there about the overclock and the filter bug. I know that VitaGL is working now in things like VitaQuake, but to get that driver into Retroarch would require adding support to the individual cores as well as the main Vita branch, I would expect they are working on it but its a big undertaking.

**Comment by ghost** [comment]
Retroarch for vita should overclock automatically at boot of app: https://github.com/libretro/RetroArch/blob/03854a0da137958589e04bd2e52b4de4a388475d/frontend/drivers/platform_psp.c#L290

If is not, i'm suggesting opening issue on Retroarch  github. ;)

**Comment by joel16** [comment]
Seems like GPU isn't overclocked @kozarovv I submitted a PR, hopefully they'll merge it.

**Comment by joel16** [comment]
Ok [it has been merged](https://github.com/libretro/RetroArch/commit/af4438406d892267e74f854c7749d85e54d95641), now there's no point in using VSH with RetroArch so I'll close this.
