### ISSUE TITLE
This plugin causes slowdown in homebrew

### ISSUE THREAD

**Issue by rsn8887** [joel16/PSV-VSH-Menu#41]
The plugin causes slowdown in many homebrew emulators (fps=40 instead of 60 etc.) for example in Uae4all2 Amiga emulator, in Retroarch, and PFBA emulator.

See here
https://gbatemp.net/threads/release-uae4all-amiga-emulator.450629/page-16#post-8481597

and here 
https://gbatemp.net/threads/release-uae4all-amiga-emulator.450629/page-16#post-8482604

for example.

This is a pain for devs because people complain about slowdown when it is your plugin causing this.

Please put a note on the release page that this plugin is known to cause slowdown in many homebrew apps or fix the issue.

**Comment by joel16** [comment]
This plugin has been discontinued for a while. I'll address that in the readme.
