### ISSUE TITLE
X/O on Japanese Vita.

### ISSUE THREAD

**Issue by dude22072** [joel16/PSV-VSH-Menu#7]
Even on a Japanese Vita the VSH menu uses the western style of X for selecting things and O for going back. For Japanese consoles, this should be flipped. There is a registry setting you can check to see which button should do which function, but I do not recall its name.

**Comment by joel16** [comment]
This was previously implemented (you can have a look at the commits) but initializing SceAppUtils caused a bunch of applications to crash for me when I last tested. Therefore I won't be looking into this for now. IIRC we can't use registryMgr functions in a user mode plugin either. So until I find a way around checking the enter/cancel buttons this won't be implemented.
